# Generated by Django 3.1.7 on 2021-03-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_priortity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priortity',
        ),
    ]
